// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgLYxKYqgVQdi3kMG3gLzB0gxxXfR6mEw',
    appId: '1:464942337860:android:7d0f1a7245d8f2230d5111',
    messagingSenderId: '464942337860',
    projectId: 'beacon-f5fd4',
    storageBucket: 'beacon-f5fd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC4k0HPnyOuqIN6XOvmpN4AS8RPzc5nr4',
    appId: '1:464942337860:ios:91a1b40d0ac8447d0d5111',
    messagingSenderId: '464942337860',
    projectId: 'beacon-f5fd4',
    storageBucket: 'beacon-f5fd4.firebasestorage.app',
    androidClientId: '464942337860-iqfvbvfldcc4vf4uv2k979tq14h46fj0.apps.googleusercontent.com',
    iosClientId: '464942337860-e5hsbaud167677rluh625n8nd001bi1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.beacon',
  );

}